<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>tpl</string>
    </array>
    <key>foldingStartMarker</key>
    <string>\{.*$</string>
    <key>foldingStopMarker</key>
    <string>^.*\}</string>
    <key>keyEquivalent</key>
    <string>^~T</string>
    <key>name</key>
    <string>Templex</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>(?&lt;!")(')([^\}]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>comment.line.apostrophe.tpl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>comment.line.tpl</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>comment.line.apostrophe.tpl</string>
        <key>end</key>
        <string>\n|\}</string>
      </dict>
      <dict>
        <key>match</key>
        <string>for|if|endif|endloop|else</string>
        <key>name</key>
        <string>keyword.control.untitled</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b([0-9]+)\b</string>
        <key>name</key>
        <string>constant.numeric.untitled</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.tpl</string>
    <key>uuid</key>
    <string>F01F22AC-7CBB-11D9-9B10-000A95E13C98</string>
  </dict>
</plist>