*DefineReport(Powertrain_Mount_MKED_Report_HW13.0, PLOT_FILE_1)
    *Id("HyperWorks", "13.*", "Report")
*Parameter(PLOT_FILE_1, PLOT_FILE_1, FILENAME, "*", "write_linz.mrf")
    *BeginPage() // Page 1
        *Title("{p1w2c1.y.HWDatatype}", On)
        *TitleFont("Arial", 1, 0, 12)
        *Layout(2)
        *BeginAnimator(Transient)
            *CurrentTime(Undeformed)
            *StartTime(0,0)
            *EndTime(6,0)
            *Increment(Forward, Frame, 1, BounceOff)
        *EndAnimator()
        *WindowIDs(12, 13)
        *ExportFormat("PNG")
        *BeginPlot()
            *PlotType(0)
            *BeginPlotHeader(On)
                *PrimaryFont("Arial", 0, 0, 14)
                *SecondaryFont("Arial", 0, 0, 10)
                *TertiaryFont("Arial", 0, 0, 10)
                *Color(0)
                *Text("{p1w1c1.y.HWRequest} - {p1w1c1.y.HWComponent}")
                *HeaderAlignment(2)
            *EndPlotHeader()
            *BeginPlotFooter(Off)
                *PrimaryFont("Arial", 0, 0, 10)
                *SecondaryFont("Arial", 0, 0, 10)
                *TertiaryFont("Arial", 0, 0, 10)
                *Color(0)
                *Text("{p1w1c1.y.HWRequest} - {p1w1c1.y.HWComponent}")
                *FooterAlignment(2)
            *EndPlotFooter()
            *BeginLegend(On)
                *Font("Arial", 0, 0, 8)
                *BorderWidth(1)
                *Color(0)
                *Leader(Left)
                *Location(INSIDE)
                *Position(3.89655, 91.3194, 4.86207, 80.2083)
                *AutoPosition(False)
                *Reversed(no)
            *EndLegend()
            *UniformAspectRatio(0)
            *FrameColor(66)
            *BackgroundColor(1)
            *GridLineColor(9)
            *ZeroLineColor(0)
            *BeginAxis(X, "Primary", on)
                *Label("Eigen Index")
                *Scale(Linear)
                *TicMethod(PerAxis)
                *Min(0)
                *Max(6)
                *Format(Auto)
                *Precision(5)
                *Tics(7)
                *Grids(2)
                *Color(67)
                *AutoFit(TRUE)
                *LabelFont("Arial", 0, 0, 10)
                *TicsFont("Arial", 0, 0, 8)
                *FitRange(FALSE)
            *EndAxis()
            *BeginAxis(Y, "Primary", on)
                *Label("{p1w1c1.y.HWDatatype}")
                *Scale(Linear)
                *TicMethod(PerAxis)
                *Min(0)
                *Max(100)
                *Format(Auto)
                *Precision(5)
                *Tics(11)
                *Grids(2)
                *Color(67)
                *AutoFit(TRUE)
                *LabelFont("Arial", 0, 0, 10)
                *TicsFont("Arial", 0, 0, 8)
                *FitRange(FALSE)
            *EndAxis()
            *BeginCurve(On, "{y.HWRequest} - {y.HWComponent}")
                *Line(1, 22, 1)
                *Symbol(0, 22, 1)
                *Shade(False)
                *Bar(0, 0, 2)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("X")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "X")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "X")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(X, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(Time, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(U, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(V, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("X")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "X")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "X")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *Attribute("HWLastGoodCurveName", "HWLastGoodCurveName", "String", "Part/30102 Powertrain - X")
            *EndCurve()
            *BeginCurve(On, "{y.HWRequest} - {y.HWComponent}")
                *Line(2, 18, 1)
                *Symbol(0, 18, 1)
                *Shade(False)
                *Bar(0, 0, 2)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("Y")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "Y")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Y")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(X, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(Time, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(U, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(V, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("Y")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "Y")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Y")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *Attribute("HWLastGoodCurveName", "HWLastGoodCurveName", "String", "Part/30102 Powertrain - Y")
            *EndCurve()
            *BeginCurve(On, "{y.HWRequest} - {y.HWComponent}")
                *Line(5, 55, 1)
                *Symbol(0, 55, 1)
                *Shade(False)
                *Bar(0, 0, 2)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("Z")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "Z")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Z")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(X, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(Time, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(U, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(V, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("Z")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "Z")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Z")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *Attribute("HWLastGoodCurveName", "HWLastGoodCurveName", "String", "Part/30102 Powertrain - Z")
            *EndCurve()
            *BeginCurve(On, "{y.HWRequest} - {y.HWComponent}")
                *Line(3, 46, 1)
                *Symbol(0, 46, 1)
                *Shade(False)
                *Bar(0, 0, 2)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("RXX")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "RXX")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "RXX")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(X, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(Time, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(U, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(V, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("RXX")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "RXX")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "RXX")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *Attribute("HWLastGoodCurveName", "HWLastGoodCurveName", "String", "Part/30102 Powertrain - RXX")
            *EndCurve()
            *BeginCurve(On, "{y.HWRequest} - {y.HWComponent}")
                *Line(4, 50, 1)
                *Symbol(0, 50, 1)
                *Shade(False)
                *Bar(0, 0, 2)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("RYY")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "RYY")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "RYY")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(X, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(Time, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(U, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(V, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("RYY")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "RYY")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "RYY")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *Attribute("HWLastGoodCurveName", "HWLastGoodCurveName", "String", "Part/30102 Powertrain - RYY")
            *EndCurve()
            *BeginCurve(On, "{y.HWRequest} - {y.HWComponent}")
                *Line(2, 24, 1)
                *Symbol(0, 24, 1)
                *Shade(False)
                *Bar(0, 0, 2)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("RZZ")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "RZZ")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "RZZ")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(X, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(Time, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(U, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(V, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("RZZ")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "RZZ")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "RZZ")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *Attribute("HWLastGoodCurveName", "HWLastGoodCurveName", "String", "Part/30102 Powertrain - RZZ")
            *EndCurve()
        *EndPlot()
        *ExportFormat("PNG")
        *BeginPlot()
            *PlotType(0)
            *BeginPlotHeader(On)
                *PrimaryFont("Arial", 0, 0, 14)
                *SecondaryFont("Arial", 0, 0, 10)
                *TertiaryFont("Arial", 0, 0, 10)
                *Color(0)
                *Text("Data - freq (cycle)")
                *HeaderAlignment(2)
            *EndPlotHeader()
            *BeginPlotFooter(Off)
                *PrimaryFont("Arial", 0, 0, 10)
                *SecondaryFont("Arial", 0, 0, 10)
                *TertiaryFont("Arial", 0, 0, 10)
                *Color(0)
                *Text("Data - freq (cycle)")
                *FooterAlignment(2)
            *EndPlotFooter()
            *BeginLegend(On)
                *Font("Arial", 0, 0, 8)
                *BorderWidth(1)
                *Color(0)
                *Leader(Left)
                *Location(INSIDE)
                *Position(4.81519, 11.5938, 5.9384, 11.2778)
                *AutoPosition(False)
                *Reversed(no)
            *EndLegend()
            *UniformAspectRatio(0)
            *FrameColor(66)
            *BackgroundColor(1)
            *GridLineColor(9)
            *ZeroLineColor(0)
            *BeginAxis(X, "Primary", on)
                *Label("Eigen Index")
                *Scale(Linear)
                *TicMethod(PerAxis)
                *Min(-0.5)
                *Max(6.5)
                *Format(Auto)
                *Precision(5)
                *Tics(15)
                *Grids(2)
                *Color(67)
                *AutoFit(FALSE)
                *LabelFont("Arial", 0, 0, 10)
                *TicsFont("Arial", 0, 0, 8)
                *FitRange(FALSE)
            *EndAxis()
            *BeginAxis(Y, "Primary", on)
                *Label("Eigenvalue")
                *Scale(Linear)
                *TicMethod(PerAxis)
                *Min(-1)
                *Max(12)
                *Format(Auto)
                *Precision(5)
                *Tics(14)
                *Grids(2)
                *Color(67)
                *AutoFit(TRUE)
                *LabelFont("Arial", 0, 0, 10)
                *TicsFont("Arial", 0, 0, 8)
                *FitRange(FALSE)
            *EndAxis()
            *BeginCurve(On, "{y.HWRequest} - {y.HWComponent}")
                *Line(0, 22, 1)
                *Symbol(1, 2, 1)
                *Shade(False)
                *Bar(0, 0, 2)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigenvalue")
                    *Request("Data")
                    *Component("freq (cycle)")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigenvalue")
                    *Attribute("HWRequest", "Request", "String", "Data")
                    *Attribute("HWComponent", "Component", "String", "freq (cycle)")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "freq (cycle)")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(X, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(Time, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(U, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigen Index")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigen Index")
                    *Attribute("HWRequest", "Request", "String", "Eigen Index")
                    *Attribute("HWComponent", "Component", "String", "Eigen Index")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Eigen Index")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *BeginVector(V, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("Eigenvalue")
                    *Request("Data")
                    *Component("freq (cycle)")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "Eigenvalue")
                    *Attribute("HWRequest", "Request", "String", "Data")
                    *Attribute("HWComponent", "Component", "String", "freq (cycle)")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "freq (cycle)")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
                *Attribute("HWLastGoodCurveName", "HWLastGoodCurveName", "String", "Data - freq (cycle)")
            *EndCurve()
        *EndPlot()
        *TimeScales(1, 1)
        *TimeDelays(0, 0)
        *AnimationEnable(1, 1)
        *SyncTolerance(2e-008)
        *SyncTableGenerationPolicy(ALL_BLOCKS)
    *EndPage()
    *BeginPage() // Page 2
        *Title("Untitled", Off)
        *TitleFont("Arial", 1, 0, 12)
        *Layout(1)
        *BeginAnimator(Transient)
            *CurrentTime(Undeformed)
            *StartTime(Undefined)
            *EndTime(Undefined)
            *Increment(Forward, Frame, 1, BounceOff)
        *EndAnimator()
        *WindowIDs(15)
        *ExportFormat("PNG")
        *BeginTableEditor()
            *NumRows(8)
            *NumCols(9)
            *BeginText()
D1,MKED; E1,MKED; F1,MKED; G1,MKED; H1,MKED; I1,MKED; B2,Frequency; D2,X; E2,Y; F2,Z; G2,Rx; H2,Ry; I2,Rz; A3,Mode 1; B3,{p1w2c1.y[1]}; D3,{p1w1c1.y[1]}; E3,{p1w1c1.y[2]}; F3,{p1w1c1.y[3]}; G3,{p1w1c1.y[4]}; H3,{p1w1c1.y[5]}; I3,{p1w1c1.y[6]}; A4,Mode 2; B4,{p1w2c1.y[2]}; D4,{p1w1c2.y[1]}; E4,{p1w1c2.y[2]}; F4,{p1w1c2.y[3]}; G4,{p1w1c2.y[4]}; H4,{p1w1c2.y[5]}; I4,{p1w1c2.y[6]}; A5,Mode 3; B5,{p1w2c1.y[3]}; D5,{p1w1c3.y[1]}; E5,{p1w1c3.y[2]}; F5,{p1w1c3.y[3]}; G5,{p1w1c3.y[4]}; H5,{p1w1c3.y[5]}; I5,{p1w1c3.y[6]}; A6,Mode 4; B6,{p1w2c1.y[4]}; D6,{p1w1c4.y[1]}; E6,{p1w1c4.y[2]}; F6,{p1w1c4.y[3]}; G6,{p1w1c4.y[4]}; H6,{p1w1c4.y[5]}; I6,{p1w1c4.y[6]}; A7,Mode 5; B7,{p1w2c1.y[5]}; D7,{p1w1c5.y[1]}; E7,{p1w1c5.y[2]}; F7,{p1w1c5.y[3]}; G7,{p1w1c5.y[4]}; H7,{p1w1c5.y[5]}; I7,{p1w1c5.y[6]}; A8,Mode 6; B8,{p1w2c1.y[6]}; D8,{p1w1c6.y[1]}; E8,{p1w1c6.y[2]}; F8,{p1w1c6.y[3]}; G8,{p1w1c6.y[4]}; H8,{p1w1c6.y[5]}; I8,{p1w1c6.y[6]}; 
            *EndText()
            *BeginProperty()
                *BeginColumnProperty()
                    *BeginData(0)
80,80,80,80,79,80,80,80,84
                    *EndData()
                *EndColumnProperty()
                *BeginRowProperty()
                    *BeginData(0)
0,0,0,0,0,0,0,0
                    *EndData()
                *EndRowProperty()
                *BeginCellProperty()
                    *BeginData(0)

                    *EndData()
                *EndCellProperty()
            *EndProperty()
            *BeginRule()
                *BeginData(1)
2,70,,0,3,D3 E3 F3 G3 H3 I3 D4 E4 F4 G4 H4 I4 D5 E5 F5 G5 H5 I5 D6 E6 F6 G6 H6 I6 D7 E7 F7 G7 H7 I7 D8 E8 F8 G8 H8 I8; 
                *EndData()
            *EndRule()
        *EndTableEditor()
        *TimeScales(1)
        *TimeDelays(0)
        *AnimationEnable(1)
        *SyncTolerance(2e-008)
        *SyncTableGenerationPolicy(ALL_BLOCKS)
    *EndPage()
    *BeginPage() // Page 3
        *Title("Untitled", Off)
        *TitleFont("Arial", 1, 0, 12)
        *Layout(1)
        *BeginAnimator(Transient)
            *CurrentTime(Undeformed)
            *StartTime(Undefined)
            *EndTime(Undefined)
            *Increment(Forward, Frame, 1, BounceOff)
        *EndAnimator()
        *WindowIDs(17)
        *ExportFormat("PNG")
        *BeginPlot()
            *PlotType(1)
            *BarchartStyle(0, 0, 20, 0, 0)
            *BarLabelFormat(Auto, 4)
            *BarLabelFont("Arial", 0, 0, 8)
            *BeginLegend(On)
                *Font("Arial", 0, 0, 10)
                *BorderWidth(1)
                *Color(0)
                *Leader(Left)
                *Location(BELOW)
                *AutoPosition(False)
                *Reversed(no)
            *EndLegend()
            *UniformAspectRatio(0)
            *FrameColor(66)
            *BackgroundColor(1)
            *GridLineColor(9)
            *ZeroLineColor(0)
            *BeginAxis(CAT, "Category", on)
                *Label("Mode 1  = {p1w2c1.y[1]} Hz   Mode 2  = {p1w2c1.y[2]} Hz   Mode 3  = {p1w2c1.y[3]} Hz   Mode 4  = {p1w2c1.y[4]} Hz   Mode 5  = {p1w2c1.y[5]} Hz    Mode 6  = {p1w2c1.y[6]} Hz")
                *Scale(Linear)
                *TicMethod(Increment)
                *Min(0)
                *Max(7)
                *Format(Auto)
                *Precision(3)
                *Increment(1)
                *Grids(1)
                *Color(67)
                *AutoFit(FALSE)
                *LabelFont("Arial", 0, 0, 12)
                *TicsFont("Arial", 0, 0, 8)
                *FitRange(FALSE)
                *Category("0")
                *Category("Mode 1")
                *Category("Mode 2")
                *Category("Mode 3")
                *Category("Mode 4")
                *Category("Mode 5")
                *Category("Mode 6")
                *HorizontalLabeling(FALSE)
                *MetaData("DEFINECURVES_CATEGORY_BUFFER", "DEFINECURVES_CATEGORY_BUFFER", "0 {Mode 1} {Mode 2} {Mode 3} {Mode 4} {Mode 5} {Mode 6}")
            *EndAxis()
            *BeginAxis(Y, "Primary", on)
                *Label("Y Axis")
                *Scale(Linear)
                *TicMethod(PerAxis)
                *Min(0)
                *Max(120)
                *Format(Auto)
                *Precision(5)
                *Tics(7)
                *Grids(2)
                *Color(67)
                *AutoFit(TRUE)
                *LabelFont("Arial", 0, 0, 10)
                *TicsFont("Arial", 0, 0, 8)
                *FitRange(FALSE)
            *EndAxis()
            *BeginCurve(On, "X")
                *Line(0, 22, 1)
                *Symbol(0, 22, 1)
                *Shade(False)
                *Bar(1, 0, 22)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("X")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "X")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "X")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
            *EndCurve()
            *BeginCurve(On, "Y")
                *Line(0, 18, 1)
                *Symbol(0, 18, 1)
                *Shade(False)
                *Bar(1, 0, 18)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("Y")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "Y")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Y")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
            *EndCurve()
            *BeginCurve(On, "Z")
                *Line(0, 55, 1)
                *Symbol(0, 55, 1)
                *Shade(False)
                *Bar(1, 0, 55)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("Z")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "Z")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "Z")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
            *EndCurve()
            *BeginCurve(On, "Rx")
                *Line(0, 46, 1)
                *Symbol(0, 46, 1)
                *Shade(False)
                *Bar(1, 0, 46)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("RXX")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "RXX")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "RXX")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
            *EndCurve()
            *BeginCurve(On, "Ry")
                *Line(0, 50, 1)
                *Symbol(0, 50, 1)
                *Shade(False)
                *Bar(1, 0, 50)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("RYY")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "RYY")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "RYY")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
            *EndCurve()
            *BeginCurve(On, "Rz")
                *Line(0, 54, 1)
                *Symbol(0, 54, 1)
                *Shade(False)
                *Bar(1, 0, 0)
                *ShowInLegend(True)
                *LayerNumber(2)
                *BeginVector(Y, File)
                    *Filename(PLOT_FILE_1)
                    *Datatype("% distribution of Kinetic Energy")
                    *Request("Part/30102 Powertrain")
                    *Component("RZZ")
                    *ScaleFactor("1")
                    *Offset("0")
                    *AxisIndex(1)
                    *Attribute("HWReaderHints", "HWReaderHints", "String", "(USE_RXRESULT_READER_FOR_DSY)")
                    *Attribute("HWFile", "File", "String", PLOT_FILE_1)
                    *Attribute("HWSolver", "Solver", "String", "MotionSolve")
                    *Attribute("HWDatatype", "Datatype", "String", "% distribution of Kinetic Energy")
                    *Attribute("HWRequest", "Request", "String", "Part/30102 Powertrain")
                    *Attribute("HWComponent", "Component", "String", "RZZ")
                    *Attribute("HWComplexComponent", "ComplexComponent", "String", "RZZ")
                    *Attribute("HWReader", "Reader", "String", "hgmrf.exe")
                *EndVector()
            *EndCurve()
            *BeginNote(On, "Note 1")
                *Attach(Window)
                *Position(0.448276, 0.00357782)
                *Text("Mode 1  = {p1w2c1.y[1]} Hz")
                *Text("Mode 2  = {p1w2c1.y[2]} Hz")
                *Text("Mode 3  = {p1w2c1.y[3]} Hz")
                *Text("Mode 4  = {p1w2c1.y[4]} Hz")
                *Text("Mode 5  = {p1w2c1.y[5]} Hz")
                *Text("Mode 6  = {p1w2c1.y[6]} Hz")
                *Font("Arial", 1, 0, 9)
                *Color(0)
                *AutoPosition(True)
                *Embedded(False)
                *BorderWidth(1)
                *NoteAlignment(Left)
                *LayerNumber(2)
            *EndNote()
            *BeginDatumLine(h, "Datum 1", on)
                *Label("Modal Purity > 70%")
                *Position("70")
                *AxisIndex(1)
                *LabelLocation(0)
                *Style(1)
                *Thickness(4)
                *Color(2)
                *LabelFont("Arial", 0, 0, 10)
                *LayerNumber(2)
                *AssociatedComponent(4)
                *MetaData("HWUnit", "HWUnit", , empty)
                *MetaData("HWUnitType", "HWUnitType", , empty)
            *EndDatumLine()
        *EndPlot()
        *TimeScales(1)
        *TimeDelays(0)
        *AnimationEnable(1)
        *SyncTolerance(2e-008)
        *SyncTableGenerationPolicy(ALL_BLOCKS)
    *EndPage()
    *BeginEntityTagTable()
        *BeginEntityTag("Page_1", "Text", hwIPage:p1)
        *EndEntityTag()
        *BeginEntityTag("Page_2", "Text", hwIPage:p2)
        *EndEntityTag()
        *BeginEntityTag("Page_3", "Text", hwIPage:p3)
        *EndEntityTag()
        *BeginEntityTag("Plot_1_1", "Window", hwIWindow:p1w1)
        *EndEntityTag()
        *BeginEntityTag("Plot_3_1", "Window", hwIWindow:p3w1)
        *EndEntityTag()
        *BeginEntityTag("Table_2_1", "Window", hwIWindow:p2w1)
        *EndEntityTag()
    *EndEntityTagTable()
*EndDefine()























